#!/bin/sh
set -e

case "$1" in
    start)
       echo "Prime DNS Server Set."
       echo "nameserver 8.8.8.8" >> /run/resolv.conf
       echo "nameserver 8.8.4.4" >> /run/resolv.conf
       echo "# Primed DNS Set."
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
