#!/bin/sh

case "$1" in
    start)
        /usr/sbin/crond -c /etc/crontabs
        ;;
    stop)
        /usr/bin/killall crond
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
