#!/bin/sh
# Set the cpu frequency governor and minimum and maximum frequencies

case "$1" in
    start)
        echo "interactive" > \
	    /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
        echo "1938000" > \
	    /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
        echo "312000" > \
	    /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        exit 1
        ;;
esac
