#!/bin/sh

case "$1" in
  start)
        ;;
  stop)
        printf "Upload logs..."
        /usr/bin/jibo-log-client-async --credentials /var/jibo/credentials.json --file /var/log/messages
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

